#!/bin/sh /etc/rc.common

START=55
STOP=10

start()
{
if [ $(uci get mentohust-sysu.@option[0].enable) ] ;
then
	echo [MentoHUST] > /etc/mentohust-sysu.conf
	echo Username=$(uci get mentohust-sysu.@mentohust-sysu[0].Username) >> /etc/mentohust-sysu.conf
	echo Password=$(uci get mentohust-sysu.@mentohust-sysu[0].Password) >> /etc/mentohust-sysu.conf
	echo Nic=$(uci get mentohust-sysu.@mentohust-sysu[0].Nic) >> /etc/mentohust-sysu.conf
	echo IP=$(uci get mentohust-sysu.@mentohust-sysu[0].IP) >> /etc/mentohust-sysu.conf
	echo Mask=$(uci get mentohust-sysu.@mentohust-sysu[0].Mask) >> /etc/mentohust-sysu.conf
	echo Gateway=$(uci get mentohust-sysu.@mentohust-sysu[0].Gateway) >> /etc/mentohust-sysu.conf
	echo DNS=$(uci get mentohust-sysu.@mentohust-sysu[0].DNS) >> /etc/mentohust-sysu.conf
	echo PingHost=$(uci get mentohust-sysu.@mentohust-sysu[0].PingHost) >> /etc/mentohust-sysu.conf
	echo Timeout=$(uci get mentohust-sysu.@mentohust-sysu[0].Timeout) >> /etc/mentohust-sysu.conf
	echo EchoInterval=$(uci get mentohust-sysu.@mentohust-sysu[0].EchoInterval) >> /etc/mentohust-sysu.conf
	echo RestartWait=$(uci get mentohust-sysu.@mentohust-sysu[0].RestartWait) >> /etc/mentohust-sysu.conf
	echo MaxFail=$(uci get mentohust-sysu.@mentohust-sysu[0].MaxFail) >> /etc/mentohust-sysu.conf
	echo StartMode=$(uci get mentohust-sysu.@mentohust-sysu[0].StartMode) >> /etc/mentohust-sysu.conf
	echo DhcpMode=$(uci get mentohust-sysu.@mentohust-sysu[0].DhcpMode) >> /etc/mentohust-sysu.conf
	echo DaemonMode=$(uci get mentohust-sysu.@mentohust-sysu[0].DaemonMode) >> /etc/mentohust-sysu.conf
	echo Version=$(uci get mentohust-sysu.@mentohust-sysu[0].Version) >> /etc/mentohust-sysu.conf
	echo DataFile=$(uci get mentohust-sysu.@mentohust-sysu[0].DataFile) >> /etc/mentohust-sysu.conf
	echo dhcpscript=$(uci get mentohust-sysu.@mentohust-sysu[0].dhcpscript) >> /etc/mentohust-sysu.conf
	mentohust-sysu >/dev/null 2>&1
else
	stop
fi

if [ $(uci get mentohust-sysu.@option[0].boot) ] ;
then
	/etc/init.d/mentohust-sysu enable
else
	/etc/init.d/mentohust-sysu disable
fi
}

stop()
{
sync
mentohust-sysu -k >/dev/null 2>&1
}

restart()
{
stop
start
}
